# Generated by Django 3.2.4 on 2021-07-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Six',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_start', models.IntegerField(default=0)),
                ('range_end', models.IntegerField(default=0)),
                ('grade', models.CharField(max_length=200)),
                ('photo', models.ImageField(default='', upload_to='grade_pictures')),
            ],
        ),
    ]
